### ISSUE TITLE
Filtering ignores 'repo' filter when 'branch' matches

### ISSUE THREAD

**Issue by ghost** [danheberden/gith#9]
We have a situation where we have multiple platforms that all have a 'master' branch, that trigger their own build job on our CI machines. Each platform has its own repository on Github.

It turns out that a change on 'master' to one of the repo's ends up triggering the payload for all repositories with the same branch name.

As a workaround, we are double checking the value of `payload.repo` against the repo we're supposed to receive the hook from.

**Comment by agnoster** [comment]
Looks like the culprit is here: https://github.com/danheberden/gith/blob/master/lib/gith.js#L44

It only checks that _some_ of the filter predicates pass, rather than all of them. Odd.

EDIT: I was wrong, turns out it's just that the result of `checksPassed` is overwritten on each filter, rather than combined via `&&`. Fixed in PR #10.

**Comment by danheberden** [comment]
https://github.com/danheberden/gith/commit/bf4d5adf32e3813f4218f50a81b0746d917c7601
